import { LocaleContextProvider } from '@/context/LocaleContext';
import BasicLayout from '@/layouts/BasicLayout/BasicLayout';
import '@/styles/globals.scss';
import Head from 'next/head';

function MyApp({ Component, pageProps }) {
    return (
        <LocaleContextProvider>
            <Head>
                <title>Vegan Life Festival | Qanibal</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <BasicLayout>
                <Component {...pageProps} />
            </BasicLayout>
        </LocaleContextProvider>
    );
}

export default MyApp;
