import BasicLayout from "@/layouts/BasicLayout/BasicLayout";
import "@/styles/globals.scss";
import Head from "next/head";

function MyApp({ Component, pageProps }) {
	return (
		<>
			<Head>
				<title>Vegan Life Festival | Qanibal</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<BasicLayout>
				<Component {...pageProps} />
			</BasicLayout>
		</>
	);
}

export default MyApp;
